// src/constants/regions.ts

export const Regions = [
  { value: "RU-ALT", name: "Алтайский край" },
  { value: "RU-AMU", name: "Амурская область" },
  { value: "RU-ARK", name: "Архангельская область" },
  { value: "RU-AST", name: "Астраханская область" },
  { value: "RU-BEL", name: "Белгородская область" },
  { value: "RU-BRY", name: "Брянская область" },
  { value: "RU-VLA", name: "Владимирская область" },
  { value: "RU-VGG", name: "Волгоградская область" },
  { value: "RU-VLG", name: "Вологодская область" },
  { value: "RU-VOR", name: "Воронежская область" },
  { value: "RU-YEV", name: "Еврейская автономная область" },
  { value: "RU-ZAB", name: "Забайкальский край" },
  { value: "RU-IVA", name: "Ивановская область" },
  { value: "RU-IRK", name: "Иркутская область" },
  { value: "RU-KB", name: "Кабардино-Балкарская Республика" },
  { value: "RU-KGD", name: "Калининградская область" },
  { value: "RU-KLU", name: "Калужская область" },
  { value: "RU-KAM", name: "Камчатский край" },
  { value: "RU-KC", name: "Карачаево-Черкесская Республика" },
  { value: "RU-KEM", name: "Кемеровская область" },
  { value: "RU-KIR", name: "Кировская область" },
  { value: "RU-KOS", name: "Костромская область" },
  { value: "RU-KDA", name: "Краснодарский край" },
  { value: "RU-KYA", name: "Красноярский край" },
  { value: "RU-KGN", name: "Курганская область" },
  { value: "RU-KRS", name: "Курская область" },
  { value: "RU-LEN", name: "Ленинградская область" },
  { value: "RU-LIP", name: "Липецкая область" },
  { value: "RU-MAG", name: "Магаданская область" },
  { value: "RU-MOS", name: "Московская область" },
  { value: "RU-MUR", name: "Мурманская область" },
  { value: "RU-NIZ", name: "Нижегородская область" },
  { value: "RU-NGR", name: "Новгородская область" },
  { value: "RU-NVS", name: "Новосибирская область" },
  { value: "RU-OMS", name: "Омская область" },
  { value: "RU-ORE", name: "Оренбургская область" },
  { value: "RU-ORL", name: "Орловская область" },
  { value: "RU-PNZ", name: "Пензенская область" },
  { value: "RU-PER", name: "Пермский край" },
  { value: "RU-PRI", name: "Приморский край" },
  { value: "RU-PSK", name: "Псковская область" },
  { value: "RU-AD", name: "Республика Адыгея" },
  { value: "RU-AL", name: "Республика Алтай" },
  { value: "RU-BA", name: "Республика Башкортостан" },
  { value: "RU-BU", name: "Республика Бурятия" },
  { value: "RU-DA", name: "Республика Дагестан" },
  { value: "RU-IN", name: "Республика Ингушетия" },
  { value: "RU-KL", name: "Республика Калмыкия" },
  { value: "RU-KR", name: "Республика Карелия" },
  { value: "RU-KO", name: "Республика Коми" },
  { value: "RU-ME", name: "Республика Марий Эл" },
  { value: "RU-MO", name: "Республика Мордовия" },
  { value: "RU-SA", name: "Республика Саха (Якутия)" },
  { value: "RU-SE", name: "Республика Северная Осетия — Алания" },
  { value: "RU-TA", name: "Республика Татарстан" },
  { value: "RU-TY", name: "Республика Тыва" },
  { value: "RU-KK", name: "Республика Хакасия" },
  { value: "RU-ROS", name: "Ростовская область" },
  { value: "RU-RYA", name: "Рязанская область" },
  { value: "RU-SAM", name: "Самарская область" },
  { value: "RU-SAR", name: "Саратовская область" },
  { value: "RU-SAK", name: "Сахалинская область" },
  { value: "RU-SVE", name: "Свердловская область" },
  { value: "RU-SMO", name: "Смоленская область" },
  { value: "RU-STA", name: "Ставропольский край" },
  { value: "RU-TAM", name: "Тамбовская область" },
  { value: "RU-TVE", name: "Тверская область" },
  { value: "RU-TOM", name: "Томская область" },
  { value: "RU-TUL", name: "Тульская область" },
  { value: "RU-TYU", name: "Тюменская область" },
  { value: "RU-UD", name: "Удмуртская Республика" },
  { value: "RU-ULY", name: "Ульяновская область" },
  { value: "RU-KHA", name: "Хабаровский край" },
  { value: "RU-CHE", name: "Челябинская область" },
  { value: "RU-CE", name: "Чеченская Республика" },
  { value: "RU-CU", name: "Чувашская Республика" },
  { value: "RU-CHU", name: "Чукотский автономный округ" },
  { value: "RU-YAR", name: "Ярославская область" },
  { value: "RU-SPE", name: "Санкт-Петербург" },
  { value: "RU-MOW", name: "Москва" },
  { value: "RU-NEN", name: "Ненецкий автономный округ" },
  { value: "RU-KHM", name: "Ханты-Мансийский автономный округ" },
  { value: "RU-YAN", name: "Ямало-Ненецкий автономный округ" },
  { value: "RU-SEV", name: "Севастополь" },
  { value: "RU-KRY", name: "Республика Крым" },
];
